#! /usr/bin/env sh

argc=$#

# This script takes any file with a filename
# comprising a "yyyymmdd_" prefix, where
# yyyy, mm, dd represent the year, month, date,
# respectively.
# Assuming the prefix conforms to ISO 8601,
# the file will be moved to directory yyyymmdd/.
#
# If there is no underscore in the filename,
# no directory will be created and the file
# will remain in its current directory.
# (File systems do not allow zero-length filenames.)

if [ $argc -lt 1 ]
then
	echo "Usage: \n\t$0 <yyyymmdd_------.ext>"
	exit
fi

media="$1"
if test -d "$media"
then
	echo "'$media' is a directory. Skipping..." > /dev/stderr
	exit 1
fi

nameprefix=`ls "$media"|cut -d "_" -f 1`

if test -d "$nameprefix"
then
	mv -nv "$media" "$nameprefix"/
else
	mkdir "$nameprefix" && \
	mv -nv "$media" "$nameprefix"/
fi
